#SALES DATA SQL PORTFOLIO FOR DATA ANALYST

create database monthly_sales;
use monthly_sales;

select * from retail_sales;

# 1.Total no of orders
SELECT COUNT(*) FROM retail_sales;

# 2.Display all records where DeliveryStatus is 'Processing'
select *
from retail_sales
where DeliveryStatus = 'Processing';
 
# 3.Count processing orders
select Deliverystatus, COUNT(*) AS Total_Processing
FROM retail_sales
WHERE DeliveryStatus = 'Processing'
GROUP BY DeliveryStatus;

# 4.Check for missing values in key columns
SELECT 
    SUM(CASE WHEN CustomerName IS NULL THEN 1 ELSE 0 END) AS Missing_Names,
    SUM(CASE WHEN Revenue IS NULL THEN 1 ELSE 0 END) AS Missing_Revenue,
    SUM(CASE WHEN PaymentMethod IS NULL THEN 1 ELSE 0 END) AS Missing_Payment
FROM retail_sales;

# 5. show only orderID, customername, and revenue
select OrderID, CustomerName, Revenue 
From retail_sales;

# 6. Find all orders placed in may
select *
from retail_sales
where month = 'May';

# 7. Display Orders where CustomerRating > 4.5
SELECT *
FROM retail_sales
WHERE CustomerRating > 4.5;

# 8. find all orders paid using UPI
select * 
from retail_sales
where paymentMethod ='UPI';

# 9.Count of orders paid via UPI
 SELECT PaymentMethod,
COUNT(*) AS Total_Payments
FROM retail_sales
WHERE PaymentMethod='UPI'
GROUP BY PaymentMethod;

# 10. show orders from Bangalore
select *
FROM retail_sales
where City = 'Bangalore';

# 11. display products whose price is greater than rupees-1000
select * 
from retail_sales
where Price > 1000;

# 12. total revenue generated
SELECT SUM(Revenue) AS Total_Revenue
FROM retail_sales;

# 13. find the average customer rating
select avg(CustomerRating) as AVERAGE_RATING
from retail_sales;

# 14. Round of average of customer rating
select round(avg(CustomerRating),2 ) AS AVERAGE_RATING
from retail_sales;

# 15. find the highest and lowest product price
 SELECT
MAX(Price) AS Highest_Price,
MIN(Price) AS Lowest_Price
FROM retail_sales;

# 16. count orders by delivery status
select DeliveryStatus, count(*) as delivery_status_order
from retail_sales
group by DeliveryStatus;

# 17. count orders by payment status
select paymentMethod, count(*) as total_orders
from retail_sales
group by paymentMethod;

# 18. total revenue generated by each city
SELECT City,
SUM(Revenue) AS Revenue_CityWise
FROM retail_sales
GROUP BY City;

# 19. total revenue generated by each category
 SELECT Category,
SUM(Revenue) AS Revenue_CategoryWise
FROM retail_sales
GROUP BY Category;

# 20.average rating for each category
select Category, avg(CustomerRating) AS AVG_RATING
FROM retail_sales
group by Category;

 # 21. Total quantity ordered for each category
 select Category, sum(qty) as Total_quantity_ordered 
 from retail_sales
 group by Category;
 
 # 22. Find the top 5 cities by Revenue
 select City, sum(Revenue) as Top_Revenues
 from retail_sales
 group by City
 order by Top_Revenues desc
 limit 5;
 
 # 23. Find the top 5 categories by revenue
 select Category, sum(Revenue) AS TOP_REVENUES_CATEGORIES
 from retail_sales
 group by Category
 order by TOP_REVENUES_CATEGORIES desc
 limit 5;
 
 # 24. Find the Month with highest Revenue
 select Month, sum(Revenue) as Highest_revenue
 from retail_sales
 group by Month
 order by Highest_revenue desc
 limit 1;
 
 # 25. which payment method is used the most
 select PaymentMethod, count(PaymentMethod) as most_used_paymethod
 from retail_sales
 group by PaymentMethod
 order by most_used_paymethod desc
 limit 1;
 
 # 26. Classify orders as High/Medium/Low value(case statements)
 select OrderID, Revenue,
 case
 when Revenue > 5000 then 'HIGH VALUE'
 when Revenue between 2000 and 5000 then 'MEDIUM VALUE'
 ELSE 'LOW VALUE'
 end as ORDER_CATEGORY
 from retail_sales;
 
 # 27. Rank cities by REVENUE
SELECT City, SUM(Revenue) AS Total_Revenue,
RANK() OVER (ORDER BY SUM(Revenue) DESC) AS City_Rank
FROM retail_sales
GROUP BY City;
 
 # 28. Running total of revenue ordered by date
SELECT
OrderID,
Date,
Revenue,
SUM(Revenue) OVER (ORDER BY Date, OrderID) AS Running_Total
FROM retail_sales;

# 29. Customers whose order value is above the overall average(subquery)
SELECT CustomerID, CustomerName, Revenue
FROM retail_sales
WHERE Revenue > 
(SELECT AVG(Revenue) FROM retail_sales)
ORDER BY Revenue DESC;

#30. Top 3 cities and their category-wise revenue
WITH top_cities AS (
    SELECT City, SUM(Revenue) AS Total_Revenue
    FROM retail_sales
    GROUP BY City
    ORDER BY Total_Revenue DESC
    LIMIT 3
)
SELECT s.City, s.Category, SUM(s.Revenue) AS Category_Revenue
FROM retail_sales s
JOIN top_cities t ON s.City = t.City
GROUP BY s.City, s.Category
ORDER BY s.City, Category_Revenue DESC;